openapi: 3.1.1
info:
  title: Components for Inventory API
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
      additionalProperties: false
      
    QueryParameter:
      type: object
      additionalProperties:
        oneOf:
          - type: string

  securitySchemes:
    bearerAuth: # セキュリティスキームの定義
      type: http
      scheme: bearer
      bearerFormat: JWT
