openapi: 3.1.1
info:
  title: Chip-in Inventory API
  description: |-
    これはChip-in のインベントリにアクセスするためのAPIである。
    アクセス制御は別途OPAで実装される。その仕様は inventory.rego で記述されている。
  contact:
    email: mitsuru@procube.jp
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://127.0.0.1:8080
security: 
  -  bearerAuth: []
tags:
  - $ref: './realm.openapi.yaml#/tags/0'
  - $ref: './zone.openapi.yaml#/tags/0'
  - $ref: './zone.openapi.yaml#/tags/1'
  - $ref: './virtual-host.openapi.yaml#/tags/0'
  - $ref: './routing-chain.openapi.yaml#/tags/0'
  - $ref: './hub.openapi.yaml#/tags/0'
  - $ref: './service.openapi.yaml#/tags/0'
paths:
  /realms:
    $ref: './realm.openapi.yaml#/paths/~1realms'
  /realms/{realm}:
    $ref: './realm.openapi.yaml#/paths/~1realms~1{realm}'
  /realms/{realm}/zones:
    $ref: './zone.openapi.yaml#/paths/~1realms~1{realm}~1zones'
  /realms/{realm}/zones/{zone}:
    $ref: './zone.openapi.yaml#/paths/~1realms~1{realm}~1zones~1{zone}'
  /realms/{realm}/zones/{zone}/subdomains:
    $ref: './zone.openapi.yaml#/paths/~1realms~1{realm}~1zones~1{zone}~1subdomains'
  /realms/{realm}/zones/{zone}/subdomains/{subdomain}:
    $ref: './zone.openapi.yaml#/paths/~1realms~1{realm}~1zones~1{zone}~1subdomains~1{subdomain}'
  /realms/{realm}/virtual-hosts:
    $ref: './virtual-host.openapi.yaml#/paths/~1realms~1{realm}~1virtual-hosts'
  /realms/{realm}/virtual-hosts/{virtualHost}:
    $ref: './virtual-host.openapi.yaml#/paths/~1realms~1{realm}~1virtual-hosts~1{virtualHost}'
  /realms/{realm}/routing-chains:
    $ref: './routing-chain.openapi.yaml#/paths/~1realms~1{realm}~1routing-chains'
  /realms/{realm}/routing-chains/{routingChainName}:
    $ref: './routing-chain.openapi.yaml#/paths/~1realms~1{realm}~1routing-chains~1{routingChainName}'
  /realms/{realm}/hubs:
    $ref: './hub.openapi.yaml#/paths/~1realms~1{realm}~1hubs'
  /realms/{realm}/hubs/{hubName}:
    $ref: './hub.openapi.yaml#/paths/~1realms~1{realm}~1hubs~1{hubName}'
  /realms/{realm}/hubs/{hubName}/services:
    $ref: './service.openapi.yaml#/paths/~1realms~1{realm}~1hubs~1{hubName}~1services'
  /realms/{realm}/hubs/{hubName}/services/{serviceName}:
    $ref: './service.openapi.yaml#/paths/~1realms~1{realm}~1hubs~1{hubName}~1services~1{serviceName}'
components:
  $ref: './components.openapi.yaml#/components'