openapi: 3.1.1
info:
  title: Realm Part of Chip-in Inventory API
  version: 1.0.0
  license: 
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://127.0.0.1:8080
security: 
  -  bearerAuth: []
tags:
  - name: realm
    description: マイクロサービスをグループ化するための論理的な区分。'/' などパスとして使用できない文字を含むことはできない。
paths:
  /realms:
    $ref: './paths/realms.yaml'
  /realms/{realm}:
    $ref: './paths/realm.yaml'
components:
  schemas:
    Realm:
      $ref: './schemas/Realm.yaml'
  securitySchemes:
    $ref: './components.openapi.yaml#/components/securitySchemes'
