openapi: 3.1.1
info:
  title: Service Part of Chip-in Inventory API
  version: 1.0.0
  license: 
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://127.0.0.1:8080
security: 
  -  bearerAuth: []
tags:
  - name: service
    description: SPN経由で提供されるマイクロサービス
paths:
  /realms/{realm}/hubs/{hubName}/services:
    $ref: './paths/services.yaml'
  /realms/{realm}/hubs/{hubName}/services/{serviceName}:
    $ref: './paths/service.yaml'
components:
  schemas:
    Service:
      $ref: './schemas/Service.yaml'
  securitySchemes:
    $ref: './components.openapi.yaml#/components/securitySchemes'
