openapi: 3.1.1
info:
  title: Virtual Host Part of Chip-in Inventory API
  version: 1.0.0
  license: 
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://127.0.0.1:8080
security: 
  -  bearerAuth: []
tags:
  - name: virtual-host
    description: ゾーンに紐づく仮想ホスト。
paths:
  /realms/{realm}/virtual-hosts:
    $ref: './paths/virtual-hosts.yaml'
  /realms/{realm}/virtual-hosts/{virtualHost}:
    $ref: './paths/virtual-host.yaml'
components:
  schemas:
    VirtualHost:
      $ref: './schemas/VirtualHost.yaml'
  securitySchemes:
    $ref: './components.openapi.yaml#/components/securitySchemes'
