openapi: 3.1.1
info:
  title: Zone Part of Chip-in Inventory API
  version: 1.0.0
  license: 
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://127.0.0.1:8080
security: 
  -  bearerAuth: []
tags:
  - name: zone
    description: API Gateway で外部に露出するDNS上のゾーン
  - name: subdomain
    description: ゾーンに紐づくサブドメイン。
paths:
  /realms/{realm}/zones:
    $ref: './paths/zones.yaml'
  /realms/{realm}/zones/{zone}:
    $ref: './paths/zone.yaml'
  /realms/{realm}/zones/{zone}/subdomains:
    $ref: './paths/subdomains.yaml'
  /realms/{realm}/zones/{zone}/subdomains/{subdomain}:
    $ref: './paths/subdomain.yaml'
components:
  schemas:
    Zone:
      $ref: './schemas/Zone.yaml'
    Subdomain:
      $ref: './schemas/Subdomain.yaml'
  securitySchemes:
    $ref: './components.openapi.yaml#/components/securitySchemes'
