type: object
required:
  - name
  - title
  - cacert
  - disabled
  - signingKey
description: |-
  レルムは、SPN内の論理的なグループであり、ゾーンやサブドメイン、仮想ホストなどのリソースを分離して管理するためのコンテナです。
  各レルムは、独自の設定や管理者を持ち、セキュリティやアクセス制御のために使用されます。
properties:
  name:
    type: string
    pattern: '^[a-z0-9][a-z0-9-]*$'
    description: |-
      レルムの名前。URN の一部として使用される。
      文字列は小文字英字、数字、ハイフンのみを含むことができる。
      ただし、ハイフンで始まることはできない。
      名称 "master" は予約されており、使用できない。
    example: example-realm
  title:
    type: string
    description: レルムの日本語名称です。
    example: CMSシステム
  description:
    type: string
    description: レルムの説明文です。
    example: CMSシステムのレルムです。
  urn:
    type: string
    readOnly: true
    format: urn
    description: |-
      レルムのURN。形式は `urn:chip-in:realm:{realm-name}` である。
    example: urn:chip-in:realm:example-realm
  cacert:
    type: string
    description: |-
      realm 配下の SPN hub で mTLSにおけるクライアント証明書を発行したCA局の証明書(PEM形式)の文字列
    example: |-
      -----BEGIN CERTIFICATE-----
      MIIDXTCCAkWgAwIBAgIJAL5z1Z2k5b4wMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
      ...
      -----END CERTIFICATE-----
  signingKey:
    type: string
    minLength: 24
    description: |-
      realm 配下のAPI Gateway でセッショントークンの署名に使用されるパスワード。
      使用できる文字は英字、数字、ハイフン、アンダースコアのみである。
    example: wUAMEUxCzAJBg1m4uS38-2__
  sessionTimeout:
    type: integer
    description: |-
      セッショントークンの有効期限。単位は秒で、デフォルトは 2592000  秒 (30日)。
    example: 2592000 
  administrators:
    type: array
    items:
      type: string
    description: |-
      レルムの管理者のユーザID。ユーザの管理はインベントリでは行わない。認証サービス内でのみ管理され、ここではそのIDのみを参照する。
    example:
      - chip-in-admin@example.com
  expiredAt:
    type: string
    format: date-time
    description: |-
      レルムの有効期限。ISO8601形式で指定する。
      この日時を過ぎると、レルムの disabled フラグは true となり、関連するリソースへのアクセスが制限される。
    example: '2024-12-31T23:59:59Z'
  disabled:
    type: boolean
    description: |-
      レルムが無効化されているかどうかを示すフラグ。
      true の場合、レルムは無効化されており、関連するリソースへのアクセスが制限される。
      false の場合、レルムは有効であり、通常の操作が可能である。
    example: false
additionalProperties: false
