type: object
required:
  - name
  - title
properties:
  name:
    type: string
    description: |-
      ルーティングチェーンの名前。URN の一部として使用される。
      文字列は小文字英字、数字、ハイフン、アンダースコアのみを含むことができる。
    example: cms-chain
  realm:
    type: string
    readOnly: true
    format: urn
    description: |-
      ルーティングチェインが属するレルムの名前。
    example: urn:chip-in:realm:example-realm
  urn:
    type: string
    readOnly: true
    format: urn
    description: |-
      ルーティングチェーンのurn。
    example: urn:chip-in:routing-chain:example-realm:cms-chain
  title:
    type: string
    description: |-
      ルーティングチェーンの日本語名称です。
    example: CMSシステムルーティングチェーン
  description:
    type: string
    description: |-
      ルーティングチェーンの説明文です。
      
    example: CMSシステムのWebUI を提供するルーティングチェーンです。
  rules:
    type: array
    description: |-
      ルーティングチェーンのルールのリスト。各ルールは、リクエストを処理するための条件とアクションを定義する。
      ルールは、リクエストのパスやヘッダなどを照合し、適切なアクションを実行するために使用される。
    items:
      type: object
      required:
        - match
        - action
      description: |-
        ルーティングチェーンのルール。各ルールは、リクエストを処理するための条件とアクションを定義する。
        ルールは、リクエストのパスやヘッダなどを照合し、
        適切なアクションを実行するために使用される。
      properties:
        match:
          type: string
          description: |-
            [evalexpr](https://docs.rs/evalexpr/latest/evalexpr/) の式で、リクエストのパスやヘッダなどを照合するための条件を記述する。
            '{{' と '}}' で囲む必要はなく、全体が evalexpr の式として評価される。
          example: request.path.starts_with("/api") && request.headers["X-Auth-Token"]
        action:
          oneOf:
            - $ref: './SetSessionId.yaml'
            - $ref: './CheckoutServices.yaml'
            - $ref: './Proxy.yaml'
            - $ref: './Redirect.yaml'
            - $ref: './Jump.yaml'
            - $ref: './SetVariables.yaml'
            - $ref: './SetHeaders.yaml'
additionalProperties: false
