type: object
title: SetVariables
description: |-
  evalexpr の式を評価して、変数に値を設定するアクション。
  このアクションは、リクエストやレスポンスの情報を参照して、変数に値を設定するために使用される。
required: 
  - type
  - variables
properties:
  type:
    type: string
    enum: [setVariables]
  variables:
    type: object
    description: |-
      設定する変数のキーと値のペア。
    example:
      savedCookie: "SESSION={{request.sessionID}}; Path=/; Secure; HttpOnly"
    additionalProperties:
      type: string
      description: |-
        プロパティの値が文字列で、かつ '{{' と '}}' が含まれている場合、その部分は evalexpr の式として評価される。
        evalexpr の式内では、リクエストやレスポンスの情報を参照して値を算出することができる。
        数値や booleanの場合はそのまま出力される。オブジェクトや配列の場合は、JSON文字列に変換されて出力される。
        プロパティの値が null の場合は、変数は設定されず、設定済みの変数は削除される。
additionalProperties: false