openapi: 3.1.1
info:
  title: SPN Hub Part of Chip-in Inventory API
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://127.0.0.1:8080
security:
  - bearerAuth: []
tags:
  - name: hub
    description: SPNのハブ。
paths:
  /realms/{realm}/hubs:
    put:
      tags:
        - hub
      summary: Update an existing hub.
      operationId: updateHub
      parameters:
        - name: realm
          in: path
          description: relam which hub belogs to
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existent hub in the SPN
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hub'
        required: true
      responses:
        '200':
          description: Successful operation, return the new contents.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hub'
        '400':
          description: Invalid Name supplied
        '404':
          description: Hub not found
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - hub
      summary: Add a new hub to the SPN.
      operationId: addHub
      parameters:
        - name: realm
          in: path
          description: relam which hub belogs to
          required: true
          schema:
            type: string
      requestBody:
        description: Create a new hub in the realm
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hub'
        required: true
      responses:
        '200':
          description: Successful operation, return the new contents.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hub'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      tags:
        - hub
      summary: Finds Hubs
      operationId: listHubs
      parameters:
        - name: realm
          in: path
          description: relam which hub belogs to
          required: true
          schema:
            type: string
        - name: query
          in: query
          description: Query parameters for filtering hubs
          required: false
          schema:
            $ref: '#/components/schemas/QueryParameter'
      responses:
        '200':
          description: |-
            Successful operation, returns a list of hubs.
            If no hubs are found, an empty array is returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hub'
        '400':
          description: Invalid status value
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /realms/{realm}/hubs/{hubName}:
    get:
      tags:
        - hub
      summary: Find hub by name.
      operationId: getHubByName
      parameters:
        - name: realm
          in: path
          description: relam which service belogs to
          required: true
          schema:
            type: string
        - name: hubName
          in: path
          description: Name of hub to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation, return the contents.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hub'
        '400':
          description: Invalid Name supplied
        '404':
          description: Hub not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - hub
      summary: Deletes a hub.
      operationId: deleteHub
      parameters:
        - name: realm
          in: path
          description: relam which hub belogs to
          required: true
          schema:
            type: string
        - name: hubName
          in: path
          description: Hub name to delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation, return the deleted contents.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hub'
        '400':
          description: Invalid Name value
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Hub:
      type: object
      required:
        - name
        - title
        - fqdn
        - serverCert
        - serverCertKey
      properties:
        name:
          type: string
          description: |-
            SPN Hub の名前。URN の一部として使用される。
            文字列は小文字英字、数字、ハイフン、アンダースコアのみを含むことができる。
          example: hub1
        realm:
          type: string
          readOnly: true
          format: urn
          description: SPN Hub が属する realm の URN。
          example: urn:chip-in:realm:example-realm
        urn:
          type: string
          readOnly: true
          description: |-
            SPN Hub のURN。URNは、SPN Hubを一意に識別するための文字列で、以下の形式で構成される。
            urn:chip-in:network:{realm}:{name}
          example: urn:chip-in:network:example-realm:hub1
        title:
          type: string
          description: SPN Hub の日本語名称です。
          example: CMSシステムプライベートネットワークハブ
        description:
          type: string
          description: SPN Hub の説明文です。
          example: CMSシステム用のプライベートネットワークのハブ
        fqdn:
          type: string
          description: SPN Hub のサーバのFQDN
          example: core.stg.chip-in.net
        serverPort:
          type: integer
          description: SPN Hub のサーバのポート番号。デフォルトは 443
          example: 443
        serverCert:
          type: string
          description: |-
            mTLSにおけるサーバ証明書(PEM形式)の文字列。
            SPN Hub のサーバは、この証明書を使用してクライアントとの通信を暗号化する。
          example: |-
            -----BEGIN CERTIFICATE-----
            -----END CERTIFICATE-----
        serverCertKey:
          type: string
          description: |-
            mTLSにおけるサーバ証明書の秘密鍵(PEM形式)の文字列。
            SPN Hub のサーバは、この秘密鍵を使用してクライアントとの通信を暗号化する。
          example: |-
            -----BEGIN RSA PRIVATE KEY-----
            -----END RSA PRIVATE KEY-----
      additionalProperties: false
    QueryParameter:
      type: object
      additionalProperties:
        oneOf:
          - type: string
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
      additionalProperties: false
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
