put:
  tags:
    - service
  summary: Update an existing service.
  operationId: updateService
  parameters:
    - name: realm
      in: path
      description: relam which service belogs to
      required: true
      schema:
        type: string
    - name: hubName
      in: path
      description: Name of hub which service belogs to
      required: true
      schema:
        type: string
  requestBody:
    description: Update an existent service in the SPN
    content:
      application/json:
        schema:
          $ref: '../service.openapi.yaml#/components/schemas/Service'
    required: true
  responses:
    '200':
      description: Successful operation, return the new contents.
      content:
        application/json:
          schema:
            $ref: '../service.openapi.yaml#/components/schemas/Service'
    '400':
      description: Invalid contents is supplied
    '404':
      description: Realm or SPN Hub or Service is not found
    '422':
      description: Validation exception
    default:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: "../components.openapi.yaml#/components/schemas/Error"
post:
  tags:
    - service
  summary: Add a new service to the SPN.
  operationId: addService
  parameters:
    - name: realm
      in: path
      description: relam which service belogs to
      required: true
      schema:
        type: string
    - name: hubName
      in: path
      description: Name of hub which service belogs to
      required: true
      schema:
        type: string
  requestBody:
    description: Create a new service in the realm
    content:
      application/json:
        schema:
          $ref: '../service.openapi.yaml#/components/schemas/Service'
    required: true
  responses:
    '200':
      description: Successful operation, return the new contents.
      content:
        application/json:
          schema:
            $ref: '../service.openapi.yaml#/components/schemas/Service'
    '400':
      description: Invalid contents is supplied
    '404':
      description: Realm or SPN Hub or Service is not found
    '422':
      description: Validation exception
    default:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: "../components.openapi.yaml#/components/schemas/Error"
get:
  tags:
    - service
  summary: Finds Services
  operationId: listServices
  parameters:
    - name: realm
      in: path
      description: relam which service belogs to
      required: true
      schema:
        type: string
    - name: hubName
      in: path
      description: Name of hub which service belogs to
      required: true
      schema:
        type: string
    - name: query
      in: query
      description: Query parameters for filtering services
      required: false
      schema:
        $ref: '../components.openapi.yaml#/components/schemas/QueryParameter'
  responses:
    '200':
      description: |-
        Successful operation, returns a list of services.
        If no services are found, an empty array is returned.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../service.openapi.yaml#/components/schemas/Service'
    '400':
      description: Invalid status value
    default:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: "../components.openapi.yaml#/components/schemas/Error"
